### ISSUE TITLE
cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by kalleSarraj** [elements-storage/ZXPInstaller#76]
This what is happening when trying to open the extension in iMac:
cannot be opened because the developer cannot be verified.

**Comment by hisaveliy** [comment]
Same for me

**Comment by seyoon20087** [comment]
This usually happens when the program is not signed. See issue [#44](https://github.com/guideguide/ZXPInstaller/issues/44#issuecomment-358030989) (BTW, this is a known issue).
While there are no plans to sign the app at this time you can either [adjust your security settings](https://support.apple.com/en-us/HT202491) or download it through the following command:
```
curl https://github.com/guideguide/ZXPInstaller/releases/download/1.6.3/ZXPInstaller.dmg --output ~/Downloads/ZXPInstaller.dmg -LO
```

**Comment by Eugeny** [comment]
Fixed in the latest release.
